# Generated by Django 4.2.2 on 2023-06-19 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Баланс')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Счет',
                'verbose_name_plural': 'Счета',
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата перевода денежных средств')),
                ('description', models.TextField(default='Перевод денежных средств', verbose_name='Описание перевода денежных средств')),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_account', to='payments.account', verbose_name='Счет отправителя')),
                ('to_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_account', to='payments.account', verbose_name='Счет получателя')),
            ],
            options={
                'verbose_name': 'Перевод денежных средств',
                'verbose_name_plural': 'Переводы денежных средств',
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='Replenishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=10, max_digits=12, verbose_name='Сумма пополнения счета')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата пополнения счета')),
                ('description', models.TextField(default='Пополнение счета', verbose_name='Описание пополнения')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replenishment', to='payments.account', verbose_name='Счет полнения')),
            ],
            options={
                'verbose_name': 'Пополнение',
                'verbose_name_plural': 'Пополнения',
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='Debiting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма списания')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата списания денежных средств')),
                ('description', models.TextField(default='Списание со счета', verbose_name='Описание списания')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debiting', to='payments.account', verbose_name='Счет')),
            ],
            options={
                'verbose_name': 'Списание',
                'verbose_name_plural': 'Списания',
                'ordering': ('date',),
            },
        ),
    ]
